package calino.malinov.ski.platform.assistant

import android.content.ComponentName
import android.content.Context
import android.content.pm.PackageManager

/**
 * Whether assistants may use Calino's app functions.
 *
 * The switch *is* the service component's enabled state, not a preference
 * beside it. The manifest ships the service disabled, and Android indexes no
 * app functions for a disabled service, so while this is off an assistant
 * cannot call Calino or even see that it offers anything. Keeping one source
 * of truth means the Settings row and what the OS exposes can never disagree.
 */
object AssistantAccess {

    /** Generated by the AppFunctions compiler from [BaseCalinoAppFunctionService]. */
    private const val ServiceClass = "calino.malinov.ski.platform.assistant.CalinoAppFunctionService"

    private fun component(context: Context) = ComponentName(context.packageName, ServiceClass)

    fun isEnabled(context: Context): Boolean =
        context.packageManager.getComponentEnabledSetting(component(context)) ==
            PackageManager.COMPONENT_ENABLED_STATE_ENABLED

    fun setEnabled(context: Context, enabled: Boolean) {
        context.packageManager.setComponentEnabledSetting(
            component(context),
            if (enabled) PackageManager.COMPONENT_ENABLED_STATE_ENABLED
            else PackageManager.COMPONENT_ENABLED_STATE_DEFAULT,
            PackageManager.DONT_KILL_APP,
        )
    }
}
